### PR TITLE
Add Who's Using Aya Section

### PR DESCRIPTION
**Pull request by dave-tucker**
Signed-off-by: Dave Tucker <dave@dtucker.co.uk>

### CODE REVIEW

**Comment by dave-tucker** [comment]
@vadorovsky and @kakkoyun, would like a +1 from both of you before I merge this :wink:

**Comment by alessandrod** [comment]
Pulsar uses aya too https://github.com/Exein-io/pulsar

**Comment by vadorovsky** [comment]
+1 for Deepfence

There one more example which I would mention:

* https://github.com/kentik/convis

**Comment by dave-tucker** [comment]
Ok, I added Exein. Once this merges, I think we should encourage others to add their own logos here :joy:

**Review by kakkoyun — APPROVED** [review]

**Comment by kakkoyun** [comment]
+1 for @parca-dev :heart:

**Review by vadorovsky — APPROVED** [review]

**Pull request merged**
